<a href="https://colab.research.google.com/github/Pushpalptha/Data-Analysis/blob/main/DATA_ANALYSIS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.arange(10,50)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
np.ones([2,2], dtype=np.int)

<ipython-input-5-b2fe104d15dd>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones([2,2], dtype=np.int)


array([[1, 1],
       [1, 1]])

In [ ]:
np.ones([3,2], dtype=np.float)

<ipython-input-6-06da4d8ebb5c>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones([3,2], dtype=np.float)


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
X = np.arange(4, dtype=np.int)
np.ones_like(X)

<ipython-input-7-0f7d7bcbfc53>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = np.arange(4, dtype=np.int)


array([1, 1, 1, 1])

In [ ]:
X = np.array([[1,2,3], [4,5,6]], dtype=np.int)
np.zeros_like(X)

<ipython-input-8-4c76cc471dbe>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = np.array([[1,2,3], [4,5,6]], dtype=np.int)


array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
X=np.array([[1,2,3],[4,5,6]], dtype=np.int)
np.ones_like(X)

<ipython-input-12-126853177fa3>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X=np.array([[1,2,3],[4,5,6]], dtype=np.int)


array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.ones([2,2] ,dtype=np.int) *2

<ipython-input-16-8250b222d902>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones([2,2] ,dtype=np.int) *2


array([[2, 2],
       [2, 2]])

In [ ]:
X = np.array([[2,3], [6,2]], dtype=np.int)
np.ones_like(X) * 7


<ipython-input-14-6c561a13a821>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = np.array([[2,3], [6,2]], dtype=np.int)


array([[7, 7],
       [7, 7]])

In [ ]:
np.ones([4,4] ,dtype=np.int)*5

<ipython-input-17-2e6ce751e8b5>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones([4,4] ,dtype=np.int)*5


array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.randint(2, size=3)

array([0, 1, 0])

In [ ]:
np.random.randn(3,3,3)


array([[[-0.54019866,  2.15297123,  0.57486642],
        [-1.46186828,  0.13870584, -0.13036688],
        [-0.74363003, -0.76357441, -0.20179447]],

       [[ 0.44436289, -0.30809799, -1.14566181],
        [ 0.17466443,  1.35826907,  0.60464518],
        [ 1.22669088, -0.64474621,  1.1528131 ]],

       [[-0.29498163, -0.43832201,  0.70033231],
        [-0.85862789, -0.42758875,  2.49642893],
        [-0.51934464,  0.74736308, -1.77506018]]])

In [ ]:
x=[1,2,3,4]
print(x, type(x))

y=[3,4,5,6]
print(y, type(y))

[1, 2, 3, 4] <class 'list'>
[3, 4, 5, 6] <class 'list'>


In [ ]:
x=np.array([5,6,7], dtype=np.int)
print(x, id(x))

[5 6 7] 140287990403984


<ipython-input-26-da41b3d2e6cd>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x=np.array([5,6,7], dtype=np.int)


In [ ]:
Y = np.copy(X)
print(Y, id(Y))


[[2 3]
 [6 2]] 140287990594512


In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(1, 11)[::-1]


array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))


800 bytes


In [ ]:
x=np.array(['A','B','C','D','E'])
x[-1]

'E'

In [ ]:
X = np.array(['A','B','C','D','E'])
X[0:3]


array(['A', 'B', 'C'], dtype='<U1')

In [ ]:
X = np.array(['A','B','C','D','E'])
X[1:-1]


array(['B', 'C', 'D'], dtype='<U1')

PANDAS AS SERIES AND MASK

In [ ]:
import pandas as pd

In [ ]:
pd.Series

pandas.core.series.Series

In [ ]:
X = ['A','B','C']
print(X, type(X))

Y = pd.Series(X)
print(Y, type(Y))


['A', 'B', 'C'] <class 'list'>
0    A
1    B
2    C
dtype: object <class 'pandas.core.series.Series'>


In [ ]:
X = pd.Series(['A','B','C'])

X.values

array(['A', 'B', 'C'], dtype=object)

In [ ]:
X = pd.Series([1,2,3,4,5],
              index=['first','second','third','forth','fifth'])

pd.Series(X, dtype=np.float)


<ipython-input-7-a7818c281d65>:4: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  pd.Series(X, dtype=np.float)


first     1.0
second    2.0
third     3.0
forth     4.0
fifth     5.0
dtype: float64

In [ ]:
import numpy as np

In [ ]:
X = pd.Series([4,2,5,1,3],
              index=['forth','second','fifth','first','third'])

X = X.sort_values()
X


first     1
second    2
third     3
forth     4
fifth     5
dtype: int64

In [ ]:
X = pd.Series([1,2,3,4,5],
              index=['A','B','C','D','E'])

X[0] = 34
X


A    34
B     2
C     3
D     4
E     5
dtype: int64

In [ ]:
X = pd.Series([1,2,3,4,5],
              index=['A','B','C','D','E'])

X[1:-1] = 0
X


A    1
B    0
C    0
D    0
E    5
dtype: int64

In [ ]:
X=pd.Series([-1,3,2,5,4,0-1-6])
mask = X <= 0
mask


0     True
1    False
2    False
3    False
4    False
5     True
dtype: bool

PANDAS AS DATAFRAMES

In [ ]:
import numpy as np
import pandas as np
df = pd.DataFrame({
    'Population': [35.467, 63.951, 80.94 , 60.665, 127.061, 64.511, 318.523],
    'GDP': [
        1785387,
        2833687,
        3874437,
        2167744,
        4602367,
        2950039,
        17348075
    ],
    'Surface Area': [
        9984670,
        640679,
        357114,
        301336,
        377930,
        242495,
        9525067
    ],
    'HDI': [
        0.913,
        0.888,
        0.916,
        0.873,
        0.891,
        0.907,
        0.915
    ],
    'Continent': [
        'America',
        'Europe',
        'Europe',
        'Europe',
        'Asia',
        'Europe',
        'America'
    ]
}, columns=['Population', 'GDP', 'Surface Area', 'HDI', 'Continent'])


In [ ]:
df

Population       GDP  Surface Area    HDI Continent
0      35.467   1785387       9984670  0.913   America
1      63.951   2833687        640679  0.888    Europe
2      80.940   3874437        357114  0.916    Europe
3      60.665   2167744        301336  0.873    Europe
4     127.061   4602367        377930  0.891      Asia
5      64.511   2950039        242495  0.907    Europe
6     318.523  17348075       9525067  0.915   America

In [ ]:
df.index = [
    'Canada',
    'France',
    'Germany',
    'Italy',
    'Japan',
    'United Kingdom',
    'United States',
]


In [ ]:
df

Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [ ]:
df.columns

Index(['Population', 'GDP', 'Surface Area', 'HDI', 'Continent'], dtype='object')

In [ ]:
df.info

<bound method DataFrame.info of                 Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America>

In [ ]:
df.index

Index(['Canada', 'France', 'Germany', 'Italy', 'Japan', 'United Kingdom',
       'United States'],
      dtype='object')

In [ ]:
df.size

35

In [ ]:
df.shape

(7, 5)

In [ ]:
df.describe()

Population           GDP  Surface Area       HDI
count    7.000000  7.000000e+00  7.000000e+00  7.000000
mean   107.302571  5.080248e+06  3.061327e+06  0.900429
std     97.249970  5.494020e+06  4.576187e+06  0.016592
min     35.467000  1.785387e+06  2.424950e+05  0.873000
25%     62.308000  2.500716e+06  3.292250e+05  0.889500
50%     64.511000  2.950039e+06  3.779300e+05  0.907000
75%    104.000500  4.238402e+06  5.082873e+06  0.914000
max    318.523000  1.734808e+07  9.984670e+06  0.916000

In [ ]:
df.mean()

<ipython-input-30-c61f0c8f89b5>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.mean()


Population      1.073026e+02
GDP             5.080248e+06
Surface Area    3.061327e+06
HDI             9.004286e-01
dtype: float64

In [ ]:
df.dtypes

Population      float64
GDP               int64
Surface Area      int64
HDI             float64
Continent        object
dtype: object

In [ ]:
df.dtypes.value_counts()

float64    2
int64      2
object     1
dtype: int64

In [ ]:
df.iloc[-1]

Population       318.523
GDP             17348075
Surface Area     9525067
HDI                0.915
Continent        America
Name: United States, dtype: object

In [ ]:
df.iloc[[1,1,0]]

Population      GDP  Surface Area    HDI Continent
France      63.951  2833687        640679  0.888    Europe
France      63.951  2833687        640679  0.888    Europe
Canada      35.467  1785387       9984670  0.913   America